default_context:
  project_name: 'hexaforce'
  project_slug: 'hexaforce'
  domain_main: 'hexaforce.net'
  domain_staging: 'stag.hexaforce.net'
  docker_swarm_stack_name_main: 'hexaforce-net'
  docker_swarm_stack_name_staging: 'stag-hexaforce-net'
  secret_key: '19151c83399501e56dbadb2ae236a9d94fa0c9ad35f643887f869d4b0f4a50c0'
  first_superuser: 'admin@hexaforce.net'
  first_superuser_password: '49c409032bc8ca1b95d1c945a237e484eade970d65356abf45e5a6c2e4b29b33'
  backend_cors_origins: '*'
  smtp_port: '587'
  smtp_host: 'smtp.hexaforce.io'
  smtp_user: 'no-replay'
  smtp_password: 'x7YHXQI94vkHwsqT'
  smtp_emails_from_email: 'info@hexaforce.io'
  postgres_password: 'bL6WFRpffnp5SP8d'
  pgadmin_default_user: 'admin@hexaforce.net'
  pgadmin_default_user_password: '49c409032bc8ca1b95d1c945a237e484eade970d65356abf45e5a6c2e4b29b33'
  traefik_constraint_tag: 'hexaforce.net'
  traefik_constraint_tag_staging: 'stag.hexaforce.net'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:49c409032bc8ca1b95d1c945a237e484eade970d65356abf45e5a6c2e4b29b33'
  sentry_dsn: 'https://c3283cc64ba348c4b3a1a115b5624b7d@o1148340.ingest.sentry.io/6219836'
  docker_image_prefix: 'hexaforce'
  docker_image_backend: 'hexaforce-backend'
  docker_image_celeryworker: 'hexaforcece-leryworker'
  docker_image_frontend: 'hexaforce-frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
