version: "3.8"
services:

  db:
    ports:
      - "5432:5432"

  backend:
    ports:
      - "8888:80"
    volumes:
      - ./fastapi/app:/app
    build:
      context: ./fastapi
    command: /start-reload.sh
